eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      override-system-properties: false
  jpa:
    open-in-view: false
logging:
  file:
    name: resources/${spring.application.name}/logs/${spring.application.name}.log

management:
  tracing:
    sampling:
      probability: 1.0