spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service
  #todo i cant auth without mongo properties here, btw i have same properties at customer-service.yml
  mongodb:
    username: root
    password: root
    host: localhost
    port: 27017
    database: customer
    authentication-database: admin